# Generated by Django 5.1.7 on 2025-03-08 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posizione', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('latitudine', models.DecimalField(blank=True, decimal_places=6, help_text='Latitudine in gradi decimali (es. 45.123456)', max_digits=9, null=True)),
                ('longitudine', models.DecimalField(blank=True, decimal_places=6, help_text='Longitudine in gradi decimali (es. 9.123456)', max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Apiario',
                'verbose_name_plural': 'Apiari',
            },
        ),
        migrations.CreateModel(
            name='TipoTrattamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('principio_attivo', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('istruzioni', models.TextField(blank=True, help_text="Istruzioni dettagliate per l'applicazione del trattamento", null=True)),
                ('tempo_sospensione', models.IntegerField(default=0, help_text='Giorni di sospensione prima della raccolta del miele')),
            ],
            options={
                'verbose_name': 'Tipo Trattamento',
                'verbose_name_plural': 'Tipi Trattamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Arnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('colore', models.CharField(choices=[('bianco', 'Bianco'), ('giallo', 'Giallo'), ('blu', 'Blu'), ('verde', 'Verde'), ('rosso', 'Rosso'), ('arancione', 'Arancione'), ('viola', 'Viola'), ('nero', 'Nero'), ('altro', 'Altro')], default='bianco', max_length=20)),
                ('data_installazione', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('apiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arnie', to='core.apiario')),
            ],
            options={
                'verbose_name': 'Arnia',
                'verbose_name_plural': 'Arnie',
                'unique_together': {('apiario', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ControlloArnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('telaini_scorte', models.IntegerField()),
                ('telaini_covata', models.IntegerField()),
                ('presenza_regina', models.BooleanField(default=True)),
                ('sciamatura', models.BooleanField(default=False)),
                ('data_sciamatura', models.DateField(blank=True, help_text='Data in cui si è verificata la sciamatura', null=True)),
                ('note_sciamatura', models.TextField(blank=True, help_text='Dettagli sulla sciamatura', null=True)),
                ('problemi_sanitari', models.BooleanField(default=False)),
                ('note_problemi', models.TextField(blank=True, help_text='Dettagli su eventuali problemi sanitari', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('arnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlli', to='core.arnia')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Controllo Arnia',
                'verbose_name_plural': 'Controlli Arnie',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Fioritura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pianta', models.CharField(max_length=100)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('latitudine', models.DecimalField(blank=True, decimal_places=6, help_text='Latitudine in gradi decimali (es. 45.123456)', max_digits=9, null=True)),
                ('longitudine', models.DecimalField(blank=True, decimal_places=6, help_text='Longitudine in gradi decimali (es. 9.123456)', max_digits=9, null=True)),
                ('raggio', models.IntegerField(blank=True, default=500, help_text='Raggio approssimativo della fioritura in metri', null=True)),
                ('apiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fioriture', to='core.apiario')),
            ],
            options={
                'verbose_name': 'Fioritura',
                'verbose_name_plural': 'Fioriture',
                'ordering': ['-data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('descrizione', models.CharField(max_length=200)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamenti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamenti',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='QuotaUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentuale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quota Utente',
                'verbose_name_plural': 'Quote Utenti',
            },
        ),
        migrations.CreateModel(
            name='TrattamentoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('data_fine_sospensione', models.DateField(blank=True, help_text='Data dopo la quale si può raccogliere il miele', null=True)),
                ('stato', models.CharField(choices=[('programmato', 'Programmato'), ('in_corso', 'In Corso'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='programmato', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('apiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trattamenti', to='core.apiario')),
                ('arnie', models.ManyToManyField(blank=True, help_text="Lasciare vuoto se il trattamento è per tutto l'apiario", related_name='trattamenti', to='core.arnia')),
                ('tipo_trattamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipotrattamento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trattamento Sanitario',
                'verbose_name_plural': 'Trattamenti Sanitari',
                'ordering': ['-data_inizio'],
            },
        ),
    ]
