# Generated by Django 5.1.7 on 2025-03-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arnia',
            name='colore_hex',
            field=models.CharField(default='#FFFFFF', help_text='Codice esadecimale del colore', max_length=7),
        ),
    ]
