# Generated by Django 5.1.7 on 2025-03-08 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_color_hex_to_arnia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apiario',
            name='condiviso_con_gruppo',
            field=models.BooleanField(default=False, help_text="Se abilitato, l'apiario è condiviso con tutti i membri del gruppo"),
        ),
        migrations.AddField(
            model_name='apiario',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apiari_posseduti', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('creatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruppi_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gruppo',
                'verbose_name_plural': 'Gruppi',
            },
        ),
        migrations.AddField(
            model_name='apiario',
            name='gruppo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apiari', to='core.gruppo'),
        ),
        migrations.CreateModel(
            name='InvitoGruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ruolo_proposto', models.CharField(choices=[('admin', 'Amministratore'), ('editor', 'Editor'), ('viewer', 'Visualizzatore')], default='viewer', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
                ('data_scadenza', models.DateTimeField()),
                ('stato', models.CharField(choices=[('inviato', 'Inviato'), ('accettato', 'Accettato'), ('rifiutato', 'Rifiutato'), ('scaduto', 'Scaduto')], default='inviato', max_length=20)),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviti', to='core.gruppo')),
                ('invitato_da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviti_inviati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invito Gruppo',
                'verbose_name_plural': 'Inviti Gruppo',
            },
        ),
        migrations.CreateModel(
            name='MembroGruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(choices=[('admin', 'Amministratore'), ('editor', 'Editor'), ('viewer', 'Visualizzatore')], default='viewer', max_length=20)),
                ('data_aggiunta', models.DateTimeField(auto_now_add=True)),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gruppo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro Gruppo',
                'verbose_name_plural': 'Membri Gruppo',
                'unique_together': {('utente', 'gruppo')},
            },
        ),
        migrations.AddField(
            model_name='gruppo',
            name='membri',
            field=models.ManyToManyField(related_name='gruppi', through='core.MembroGruppo', to=settings.AUTH_USER_MODEL),
        ),
    ]
