# Generated by Django 5.1.7 on 2025-03-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pagamento_gruppo_quotautente_gruppo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiario',
            name='visibilita_mappa',
            field=models.CharField(choices=[('privato', 'Solo proprietario'), ('gruppo', 'Membri del gruppo'), ('pubblico', 'Tutti gli utenti')], default='privato', help_text='Chi può visualizzare questo apiario sulla mappa', max_length=20),
        ),
    ]
