# Generated by Django 5.1.7 on 2025-03-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_immagineprofilo_profilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotrattamento',
            name='giorni_blocco_covata',
            field=models.IntegerField(default=0, help_text='Durata consigliata in giorni del blocco di covata'),
        ),
        migrations.AddField(
            model_name='tipotrattamento',
            name='nota_blocco_covata',
            field=models.TextField(blank=True, help_text='Note specifiche sul blocco di covata (ad es. metodo, tempistiche)', null=True),
        ),
        migrations.AddField(
            model_name='tipotrattamento',
            name='richiede_blocco_covata',
            field=models.BooleanField(default=False, help_text='Indica se questo trattamento richiede un blocco di covata'),
        ),
        migrations.AddField(
            model_name='trattamentosanitario',
            name='blocco_covata_attivo',
            field=models.BooleanField(default=False, help_text='Indica se il blocco di covata è attualmente attivo'),
        ),
        migrations.AddField(
            model_name='trattamentosanitario',
            name='data_fine_blocco',
            field=models.DateField(blank=True, help_text='Data prevista per la fine del blocco di covata', null=True),
        ),
        migrations.AddField(
            model_name='trattamentosanitario',
            name='data_inizio_blocco',
            field=models.DateField(blank=True, help_text='Data di inizio del blocco di covata', null=True),
        ),
        migrations.AddField(
            model_name='trattamentosanitario',
            name='metodo_blocco',
            field=models.CharField(blank=True, help_text='Metodo utilizzato per il blocco (es. ingabbiamento, rimozione regina)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trattamentosanitario',
            name='note_blocco',
            field=models.TextField(blank=True, help_text='Note sul blocco di covata', null=True),
        ),
        migrations.AlterField(
            model_name='fioritura',
            name='apiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fioriture', to='core.apiario'),
        ),
        migrations.AlterField(
            model_name='fioritura',
            name='latitudine',
            field=models.DecimalField(decimal_places=6, help_text='Latitudine in gradi decimali (es. 45.123456)', max_digits=9),
        ),
        migrations.AlterField(
            model_name='fioritura',
            name='longitudine',
            field=models.DecimalField(decimal_places=6, help_text='Longitudine in gradi decimali (es. 9.123456)', max_digits=9),
        ),
    ]
