# Generated by Django 5.1.7 on 2025-03-09 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tipotrattamento_giorni_blocco_covata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fioritura',
            name='creatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fioriture_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fioritura',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fioritura',
            name='data_modifica',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
