# Generated by Django 5.1.7 on 2025-03-11 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fioritura_creatore_fioritura_data_creazione_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Melario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telaini', models.IntegerField(default=10, help_text='Numero di telaini nel melario')),
                ('posizione', models.IntegerField(help_text='Posizione del melario (1 = più vicino al nido, ecc.)')),
                ('data_posizionamento', models.DateField()),
                ('data_rimozione', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('posizionato', 'Posizionato'), ('rimosso', 'Rimosso'), ('in_smielatura', 'In Smielatura'), ('smielato', 'Smielato')], default='posizionato', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('arnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melari', to='core.arnia')),
            ],
            options={
                'verbose_name': 'Melario',
                'verbose_name_plural': 'Melari',
                'ordering': ['arnia', 'posizione'],
            },
        ),
        migrations.CreateModel(
            name='Smielatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantita_miele', models.DecimalField(decimal_places=2, help_text='Quantità di miele in kg', max_digits=7)),
                ('tipo_miele', models.CharField(help_text='Tipo di miele/origine botanica principale', max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('data_registrazione', models.DateTimeField(auto_now_add=True)),
                ('apiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smielature', to='core.apiario')),
                ('melari', models.ManyToManyField(related_name='smielature', to='core.melario')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smielatura',
                'verbose_name_plural': 'Smielature',
                'ordering': ['-data'],
            },
        ),
    ]
