# Generated by Django 5.1.7 on 2025-03-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_melario_smielatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlloarnia',
            name='celle_reali',
            field=models.BooleanField(default=False, help_text='Sono presenti celle reali'),
        ),
        migrations.AddField(
            model_name='controlloarnia',
            name='numero_celle_reali',
            field=models.PositiveSmallIntegerField(default=0, help_text='Numero di celle reali trovate'),
        ),
        migrations.AddField(
            model_name='controlloarnia',
            name='regina_sostituita',
            field=models.BooleanField(default=False, help_text='La regina è stata sostituita durante questo controllo'),
        ),
        migrations.AddField(
            model_name='controlloarnia',
            name='regina_vista',
            field=models.BooleanField(default=False, help_text='La regina è stata vista durante il controllo'),
        ),
        migrations.AddField(
            model_name='controlloarnia',
            name='uova_fresche',
            field=models.BooleanField(default=False, help_text='Sono state viste uova fresche (indica presenza regina)'),
        ),
        migrations.CreateModel(
            name='Regina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('data_introduzione', models.DateField(help_text="Data in cui la regina è stata introdotta nell'arnia")),
                ('origine', models.CharField(choices=[('acquistata', 'Acquistata'), ('allevata', 'Allevata'), ('sciamatura', 'Sciamatura Naturale'), ('emergenza', 'Celle di Emergenza'), ('sconosciuta', 'Sconosciuta')], default='sconosciuta', max_length=20)),
                ('razza', models.CharField(choices=[('ligustica', 'Apis mellifera ligustica (Italiana)'), ('carnica', 'Apis mellifera carnica (Carnica)'), ('buckfast', 'Buckfast'), ('caucasica', 'Apis mellifera caucasica'), ('sicula', 'Apis mellifera sicula (Siciliana)'), ('ibrida', 'Ibrida'), ('altro', 'Altro')], default='ligustica', max_length=20)),
                ('codice_marcatura', models.CharField(blank=True, help_text='Codice o numero di marcatura', max_length=50, null=True)),
                ('colore_marcatura', models.CharField(choices=[('bianco', 'Bianco (anni terminanti in 1,6)'), ('giallo', 'Giallo (anni terminanti in 2,7)'), ('rosso', 'Rosso (anni terminanti in 3,8)'), ('verde', 'Verde (anni terminanti in 4,9)'), ('blu', 'Blu (anni terminanti in 5,0)'), ('non_marcata', 'Non Marcata')], default='non_marcata', max_length=20)),
                ('marcata', models.BooleanField(default=False)),
                ('fecondata', models.BooleanField(default=True, help_text='Indica se la regina è stata fecondata')),
                ('selezionata', models.BooleanField(default=False, help_text='Regina selezionata per caratteristiche genetiche')),
                ('note', models.TextField(blank=True, null=True)),
                ('docilita', models.PositiveSmallIntegerField(blank=True, help_text='Valutazione docilità (1-5)', null=True)),
                ('produttivita', models.PositiveSmallIntegerField(blank=True, help_text='Valutazione produttività (1-5)', null=True)),
                ('resistenza_malattie', models.PositiveSmallIntegerField(blank=True, help_text='Resistenza alle malattie (1-5)', null=True)),
                ('tendenza_sciamatura', models.PositiveSmallIntegerField(blank=True, help_text='Tendenza alla sciamatura (1-5)', null=True)),
                ('arnia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regina', to='core.arnia')),
                ('regina_madre', models.ForeignKey(blank=True, help_text='Regina da cui proviene (se conosciuta)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figlie', to='core.regina')),
            ],
            options={
                'verbose_name': 'Regina',
                'verbose_name_plural': 'Regine',
                'ordering': ['-data_introduzione'],
            },
        ),
        migrations.CreateModel(
            name='StoriaRegine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('motivo_fine', models.CharField(blank=True, help_text='Motivo della rimozione/morte della regina', max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('arnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storia_regine', to='core.arnia')),
                ('regina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storia', to='core.regina')),
            ],
            options={
                'verbose_name': 'Storia Regina',
                'verbose_name_plural': 'Storia Regine',
                'ordering': ['-data_inizio'],
            },
        ),
    ]
