# Generated by Django 5.1.7 on 2025-03-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_controlloarnia_celle_reali_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiario',
            name='monitoraggio_meteo',
            field=models.BooleanField(default=True, help_text='Abilita il monitoraggio meteorologico per questo apiario'),
        ),
        migrations.CreateModel(
            name='DatiMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('umidita', models.IntegerField(blank=True, null=True)),
                ('pressione', models.IntegerField(blank=True, null=True)),
                ('velocita_vento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('direzione_vento', models.IntegerField(blank=True, null=True)),
                ('descrizione', models.CharField(blank=True, max_length=100, null=True)),
                ('icona', models.CharField(blank=True, max_length=20, null=True)),
                ('pioggia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('apiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dati_meteo', to='core.apiario')),
            ],
            options={
                'verbose_name': 'Dato Meteo',
                'verbose_name_plural': 'Dati Meteo',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PrevisioneMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_previsione', models.DateTimeField()),
                ('data_riferimento', models.DateTimeField()),
                ('temperatura_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('umidita', models.IntegerField(blank=True, null=True)),
                ('pressione', models.IntegerField(blank=True, null=True)),
                ('velocita_vento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('direzione_vento', models.IntegerField(blank=True, null=True)),
                ('probabilita_pioggia', models.IntegerField(blank=True, null=True)),
                ('descrizione', models.CharField(blank=True, max_length=100, null=True)),
                ('icona', models.CharField(blank=True, max_length=20, null=True)),
                ('apiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsioni_meteo', to='core.apiario')),
            ],
            options={
                'verbose_name': 'Previsione Meteo',
                'verbose_name_plural': 'Previsioni Meteo',
                'ordering': ['data_riferimento'],
            },
        ),
    ]
