# Generated by Django 4.2.20 on 2025-03-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_apiario_monitoraggio_meteo_datimeteo_previsionemeteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlloarnia',
            name='telaini_config',
            field=models.TextField(blank=True, help_text='JSON configuration of frame types and positions', null=True),
        ),
    ]
