# Generated by Django 4.2.20 on 2026-01-29 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_controlloarnia_telaini_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attrezzatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descrizione", models.TextField(blank=True, null=True)),
                ("marca", models.CharField(blank=True, max_length=100, null=True)),
                ("modello", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "numero_serie",
                    models.CharField(
                        blank=True,
                        help_text="Numero di serie o identificativo",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "condiviso_con_gruppo",
                    models.BooleanField(
                        default=False,
                        help_text="Se abilitato, l'attrezzatura è visibile a tutto il gruppo",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("disponibile", "Disponibile"),
                            ("in_uso", "In Uso"),
                            ("manutenzione", "In Manutenzione"),
                            ("dismesso", "Dismesso"),
                            ("prestato", "Prestato"),
                        ],
                        default="disponibile",
                        max_length=20,
                    ),
                ),
                (
                    "condizione",
                    models.CharField(
                        choices=[
                            ("nuovo", "Nuovo"),
                            ("ottimo", "Ottimo"),
                            ("buono", "Buono"),
                            ("discreto", "Discreto"),
                            ("usurato", "Usurato"),
                            ("da_riparare", "Da Riparare"),
                        ],
                        default="buono",
                        max_length=20,
                    ),
                ),
                (
                    "posizione",
                    models.CharField(
                        blank=True,
                        help_text="Posizione specifica (es. magazzino, laboratorio)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "prezzo_acquisto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prezzo di acquisto in euro",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("data_acquisto", models.DateField(blank=True, null=True)),
                ("fornitore", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "garanzia_fino_a",
                    models.DateField(
                        blank=True,
                        help_text="Data di scadenza della garanzia",
                        null=True,
                    ),
                ),
                (
                    "vita_utile_anni",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Vita utile stimata in anni per ammortamento",
                    ),
                ),
                (
                    "quantita",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantità disponibile"
                    ),
                ),
                (
                    "unita_misura",
                    models.CharField(
                        default="pz",
                        help_text="Unità di misura (pz, kg, lt, ecc.)",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "immagine",
                    models.ImageField(blank=True, null=True, upload_to="attrezzature/"),
                ),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_modifica", models.DateTimeField(auto_now=True)),
                (
                    "apiario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Apiario dove si trova l'attrezzatura",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attrezzature",
                        to="core.apiario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attrezzatura",
                "verbose_name_plural": "Attrezzature",
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaAttrezzatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descrizione", models.TextField(blank=True, null=True)),
                (
                    "icona",
                    models.CharField(
                        default="bi-tools",
                        help_text="Classe icona Bootstrap (es. bi-tools, bi-box)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria Attrezzatura",
                "verbose_name_plural": "Categorie Attrezzature",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="SpesaAttrezzatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("acquisto", "Acquisto"),
                            ("manutenzione", "Manutenzione"),
                            ("riparazione", "Riparazione"),
                            ("accessori", "Accessori"),
                            ("consumabili", "Consumabili"),
                            ("altro", "Altro"),
                        ],
                        default="acquisto",
                        max_length=20,
                    ),
                ),
                ("descrizione", models.CharField(max_length=200)),
                ("importo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField()),
                ("fornitore", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "numero_fattura",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                (
                    "attrezzatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spese",
                        to="core.attrezzatura",
                    ),
                ),
                (
                    "gruppo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spese_attrezzature",
                        to="core.gruppo",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        help_text="Utente che ha registrato la spesa",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Spesa Attrezzatura",
                "verbose_name_plural": "Spese Attrezzature",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="PrestitoAttrezzatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_richiesta", models.DateTimeField(auto_now_add=True)),
                (
                    "data_inizio_prestito",
                    models.DateField(help_text="Data prevista inizio prestito"),
                ),
                (
                    "data_fine_prevista",
                    models.DateField(help_text="Data prevista restituzione"),
                ),
                (
                    "data_restituzione",
                    models.DateField(
                        blank=True,
                        help_text="Data effettiva di restituzione",
                        null=True,
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("richiesto", "Richiesto"),
                            ("approvato", "Approvato"),
                            ("in_corso", "In Corso"),
                            ("restituito", "Restituito"),
                            ("rifiutato", "Rifiutato"),
                        ],
                        default="richiesto",
                        max_length=20,
                    ),
                ),
                (
                    "motivo",
                    models.TextField(help_text="Motivo della richiesta di prestito"),
                ),
                (
                    "note_restituzione",
                    models.TextField(
                        blank=True,
                        help_text="Note sullo stato al momento della restituzione",
                        null=True,
                    ),
                ),
                ("data_approvazione", models.DateTimeField(blank=True, null=True)),
                (
                    "approvato_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prestiti_approvati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attrezzatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestiti",
                        to="core.attrezzatura",
                    ),
                ),
                (
                    "richiedente",
                    models.ForeignKey(
                        help_text="Utente che richiede il prestito",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestiti_richiesti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestito Attrezzatura",
                "verbose_name_plural": "Prestiti Attrezzature",
                "ordering": ["-data_richiesta"],
            },
        ),
        migrations.CreateModel(
            name="ManutenzioneAttrezzatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ordinaria", "Manutenzione Ordinaria"),
                            ("straordinaria", "Manutenzione Straordinaria"),
                            ("riparazione", "Riparazione"),
                            ("pulizia", "Pulizia"),
                            ("revisione", "Revisione"),
                            ("sostituzione_parti", "Sostituzione Parti"),
                        ],
                        default="ordinaria",
                        max_length=30,
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("programmata", "Programmata"),
                            ("in_corso", "In Corso"),
                            ("completata", "Completata"),
                            ("annullata", "Annullata"),
                        ],
                        default="programmata",
                        max_length=20,
                    ),
                ),
                (
                    "data_programmata",
                    models.DateField(help_text="Data prevista per la manutenzione"),
                ),
                (
                    "data_esecuzione",
                    models.DateField(
                        blank=True, help_text="Data effettiva di esecuzione", null=True
                    ),
                ),
                (
                    "descrizione",
                    models.TextField(
                        help_text="Descrizione del lavoro da eseguire/eseguito"
                    ),
                ),
                (
                    "costo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo della manutenzione in euro",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "eseguito_da",
                    models.CharField(
                        blank=True,
                        help_text="Chi ha eseguito la manutenzione",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "prossima_manutenzione",
                    models.DateField(
                        blank=True,
                        help_text="Data suggerita per la prossima manutenzione",
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                (
                    "attrezzatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manutenzioni",
                        to="core.attrezzatura",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        help_text="Utente che ha registrato la manutenzione",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manutenzione Attrezzatura",
                "verbose_name_plural": "Manutenzioni Attrezzature",
                "ordering": ["-data_programmata"],
            },
        ),
        migrations.CreateModel(
            name="InventarioAttrezzature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "descrizione",
                    models.CharField(
                        blank=True,
                        help_text="Descrizione dell'inventario (es. Inventario annuale 2024)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "valore_totale",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valore totale calcolato delle attrezzature",
                        max_digits=12,
                    ),
                ),
                (
                    "valore_residuo_totale",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valore residuo totale (dopo ammortamenti)",
                        max_digits=12,
                    ),
                ),
                ("numero_attrezzature", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True, null=True)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                (
                    "gruppo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventari",
                        to="core.gruppo",
                    ),
                ),
                (
                    "proprietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario Attrezzature",
                "verbose_name_plural": "Inventari Attrezzature",
                "ordering": ["-data"],
            },
        ),
        migrations.AddField(
            model_name="attrezzatura",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attrezzature",
                to="core.categoriaattrezzatura",
            ),
        ),
        migrations.AddField(
            model_name="attrezzatura",
            name="gruppo",
            field=models.ForeignKey(
                blank=True,
                help_text="Gruppo con cui l'attrezzatura è condivisa",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attrezzature",
                to="core.gruppo",
            ),
        ),
        migrations.AddField(
            model_name="attrezzatura",
            name="proprietario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attrezzature",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
