# Generated by Django 4.2.20 on 2026-02-12 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0013_attrezzatura_categoriaattrezzatura_spesaattrezzatura_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("indirizzo", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clienti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clienti",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="melario",
            name="peso_stimato",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso stimato in kg",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Vendita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("note", models.TextField(blank=True, null=True)),
                ("data_registrazione", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendite",
                        to="core.cliente",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendita",
                "verbose_name_plural": "Vendite",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Invasettamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("tipo_miele", models.CharField(max_length=100)),
                (
                    "formato_vasetto",
                    models.IntegerField(
                        help_text="Grammi per vasetto (250, 500, 1000)"
                    ),
                ),
                ("numero_vasetti", models.IntegerField()),
                ("lotto", models.CharField(blank=True, max_length=50, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("data_registrazione", models.DateTimeField(auto_now_add=True)),
                (
                    "smielatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invasettamenti",
                        to="core.smielatura",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invasettamento",
                "verbose_name_plural": "Invasettamenti",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="DettaglioVendita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_miele", models.CharField(max_length=100)),
                ("formato_vasetto", models.IntegerField()),
                ("quantita", models.IntegerField()),
                (
                    "prezzo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "vendita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dettagli",
                        to="core.vendita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dettaglio Vendita",
                "verbose_name_plural": "Dettagli Vendita",
            },
        ),
    ]
