# Generated by Django 4.2.20 on 2026-03-03 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0014_cliente_melario_peso_stimato_vendita_invasettamento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalisiTelaino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_telaino", models.IntegerField()),
                (
                    "facciata",
                    models.CharField(
                        choices=[("A", "Facciata A"), ("B", "Facciata B")], max_length=1
                    ),
                ),
                ("data", models.DateField(auto_now_add=True)),
                ("conteggio_api", models.IntegerField(default=0)),
                ("conteggio_regine", models.IntegerField(default=0)),
                ("conteggio_fuchi", models.IntegerField(default=0)),
                ("conteggio_celle_reali", models.IntegerField(default=0)),
                ("confidence_media", models.FloatField(default=0.0)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "immagine",
                    models.ImageField(
                        blank=True, null=True, upload_to="analisi_telaini/"
                    ),
                ),
                ("data_registrazione", models.DateTimeField(auto_now_add=True)),
                (
                    "arnia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analisi_telaini",
                        to="core.arnia",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analisi Telaino",
                "verbose_name_plural": "Analisi Telaini",
                "ordering": ["-data", "-data_registrazione"],
            },
        ),
    ]
