# Generated by Django 4.2.20 on 2026-03-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_melario_tipo_stato_favi_escludi_regina"),
    ]

    operations = [
        migrations.AddField(
            model_name="dettagliovendita",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("miele", "Miele"),
                    ("propoli", "Propoli"),
                    ("cera", "Cera"),
                    ("polline", "Polline"),
                    ("pappa_reale", "Pappa reale"),
                    ("nucleo", "Nucleo"),
                    ("regina", "Regina"),
                    ("altro", "Altro"),
                ],
                default="miele",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendita",
            name="acquirente_nome",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="vendita",
            name="canale",
            field=models.CharField(
                choices=[
                    ("mercatino", "Mercatino"),
                    ("negozio", "Negozio"),
                    ("privato", "Privato"),
                    ("online", "Online"),
                    ("altro", "Altro"),
                ],
                default="privato",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendita",
            name="pagamento",
            field=models.CharField(
                choices=[
                    ("contanti", "Contanti"),
                    ("bonifico", "Bonifico"),
                    ("carta", "Carta"),
                    ("altro", "Altro"),
                ],
                default="contanti",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dettagliovendita",
            name="formato_vasetto",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dettagliovendita",
            name="tipo_miele",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vendita",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendite",
                to="core.cliente",
            ),
        ),
    ]
