# Generated by Django 4.2.20 on 2026-03-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_nucleo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiariomaplayout",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="nucleo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
