# Generated by Django 4.2.20 on 2026-03-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_apiariomaplayout_id_alter_nucleo_id"),
        ("core", "0023_fioritura_social"),
    ]

    operations = []
