# Generated by Django 4.2.20 on 2026-03-08 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0023_fioritura_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiario",
            name="latitudine",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Latitudine in gradi decimali (es. 45.123456)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apiario",
            name="longitudine",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Longitudine in gradi decimali (es. 9.123456)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apiariomaplayout",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fioritura",
            name="latitudine",
            field=models.DecimalField(
                decimal_places=8,
                help_text="Latitudine in gradi decimali (es. 45.123456)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="fioritura",
            name="longitudine",
            field=models.DecimalField(
                decimal_places=8,
                help_text="Longitudine in gradi decimali (es. 9.123456)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="fioritura",
            name="pianta_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("spontanea", "Spontanea"),
                    ("coltivata", "Coltivata"),
                    ("alberata", "Alberata"),
                    ("arborea", "Arborea"),
                    ("arbustiva", "Arbustiva"),
                ],
                help_text="Tipo di pianta",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fiorituraconferma",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fiorituraconferma",
            name="intensita",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Scarsa"),
                    (2, "Discreta"),
                    (3, "Buona"),
                    (4, "Ottima"),
                    (5, "Eccezionale"),
                ],
                help_text="Intensità osservata dall'utente",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fiorituraconferma",
            name="nota",
            field=models.TextField(
                blank=True, help_text="Nota/osservazione dell'apicoltore", null=True
            ),
        ),
        migrations.AlterField(
            model_name="nucleo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="ControlloNucleo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "n_telaini",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Telaini occupati", null=True
                    ),
                ),
                (
                    "forza_colonia",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Forza colonia da 1 a 5", null=True
                    ),
                ),
                ("presenza_regina", models.BooleanField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                (
                    "nucleo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controlli",
                        to="core.nucleo",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Controllo Nucleo",
                "verbose_name_plural": "Controlli Nucleo",
                "ordering": ["-data"],
            },
        ),
    ]
