# Generated by Django 4.2.20 on 2026-03-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_fix_coordinate_max_digits_add_controlloNucleo"),
        ("core", "0024_merge_20260308_0919"),
    ]

    operations = []
