# Generated by Django 4.2.20 on 2026-03-11 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0024_fix_coordinate_max_digits_add_controlloNucleo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("invito_gruppo", "Invito Gruppo"),
                            ("membro_aggiunto", "Aggiunto al Gruppo"),
                            ("membro_rimosso", "Rimosso dal Gruppo"),
                            ("invito_accettato", "Invito Accettato"),
                            ("invito_rifiutato", "Invito Rifiutato"),
                            ("controllo_scaduto", "Controllo Scaduto"),
                            ("trattamento_scaduto", "Trattamento Scaduto"),
                            ("trattamento_promemoria", "Promemoria Trattamento"),
                            ("fioritura_vicina", "Fioritura Vicina"),
                            ("regina_assente", "Regina Assente"),
                            ("sistema", "Notifica di Sistema"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titolo", models.CharField(max_length=200)),
                ("messaggio", models.TextField()),
                ("letta", models.BooleanField(default=False)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("bassa", "Bassa"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "mittente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifiche_inviate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifiche",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifica",
                "verbose_name_plural": "Notifiche",
                "ordering": ["-data_creazione"],
            },
        ),
    ]
