# Generated by Django 4.2.20 on 2026-03-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_merge_20260308_0945"),
        ("core", "0025_notifica_model"),
    ]

    operations = []
