# Generated by Django 4.2.20 on 2026-03-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_notifica_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilo",
            name="gemini_api_key",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Gemini API Key personale",
            ),
        ),
    ]
