# Generated by Django 4.2.20 on 2026-03-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_merge_0025_merge_20260308_0945_0025_notifica_model"),
        ("core", "0026_profilo_gemini_api_key"),
    ]

    operations = []
