# Generated by Django 5.2.13 on 2026-04-23 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_activationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlloarnia",
            name="sostituzione_scatola",
            field=models.BooleanField(
                default=False, help_text="La scatola (corpo nido) è stata sostituita"
            ),
        ),
        migrations.AlterField(
            model_name="activationcode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="activationcode",
            name="target_tier",
            field=models.CharField(
                choices=[
                    ("free", "Base (Test)"),
                    ("apicoltore", "Sostenitore"),
                    ("professionale", "Tester Avanzato"),
                ],
                default="apicoltore",
                max_length=20,
                verbose_name="Tier da attivare",
            ),
        ),
        migrations.AlterField(
            model_name="colonia",
            name="colonia_origine",
            field=models.ForeignKey(
                blank=True,
                help_text="Colonia da cui questa proviene (divisione, sciame catturato, ecc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colonie_figlie",
                to="core.colonia",
            ),
        ),
        migrations.AlterField(
            model_name="colonia",
            name="colonia_successore",
            field=models.ForeignKey(
                blank=True,
                help_text="Colonia in cui è confluita questa, in caso di unione",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colonie_assorbite",
                to="core.colonia",
            ),
        ),
        migrations.AlterField(
            model_name="colonia",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="colonia",
            name="motivo_fine",
            field=models.TextField(
                blank=True,
                help_text="Descrizione del motivo di fine ciclo (morte, vendita, unione, ecc.)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="controlloarnia",
            name="colonia",
            field=models.ForeignKey(
                blank=True,
                help_text="Colonia ispezionata (dato biologico principale)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="controlli",
                to="core.colonia",
            ),
        ),
        migrations.AlterField(
            model_name="controllonucleo",
            name="colonia",
            field=models.ForeignKey(
                blank=True,
                help_text="Colonia ispezionata (derivato dal nucleo al momento del controllo)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="controlli_nucleo",
                to="core.colonia",
            ),
        ),
        migrations.AlterField(
            model_name="profilo",
            name="ai_requests_reset_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Reset contatore AI"
            ),
        ),
        migrations.AlterField(
            model_name="profilo",
            name="ai_requests_today",
            field=models.IntegerField(
                default=0, verbose_name="Richieste AI oggi (totale)"
            ),
        ),
        migrations.AlterField(
            model_name="profilo",
            name="ai_tier",
            field=models.CharField(
                choices=[
                    ("free", "Base (Test)"),
                    ("apicoltore", "Sostenitore"),
                    ("professionale", "Tester Avanzato"),
                ],
                default="free",
                max_length=20,
                verbose_name="Piano AI",
            ),
        ),
        migrations.AlterField(
            model_name="regina",
            name="colonia",
            field=models.OneToOneField(
                blank=True,
                help_text="Colonia di cui è regina",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="regina",
                to="core.colonia",
            ),
        ),
        migrations.AlterField(
            model_name="regina",
            name="data_introduzione",
            field=models.DateField(
                help_text="Data in cui la regina è stata introdotta nella colonia"
            ),
        ),
        migrations.AlterField(
            model_name="systemaiquota",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trattamentosanitario",
            name="arnie",
            field=models.ManyToManyField(
                blank=True,
                help_text="Legacy: box fisici — usare 'colonie' per i nuovi record",
                related_name="trattamenti",
                to="core.arnia",
            ),
        ),
    ]
