# Generated by Django 5.2.13 on 2026-05-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_arnia_nfc_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="invasettamento",
            name="numero_vasetti_venduti",
            field=models.IntegerField(
                default=0,
                help_text="Vasetti già venduti del lotto (vasetti disponibili = numero_vasetti - venduti).",
            ),
        ),
        migrations.AddField(
            model_name="smielatura",
            name="archiviata",
            field=models.BooleanField(
                default=False,
                help_text="Se True, la smielatura non appare più nelle viste attive.",
            ),
        ),
        migrations.AddField(
            model_name="smielatura",
            name="kg_trasferiti",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Kg già trasferiti in maturatori (auto-aggiornato).",
                max_digits=7,
            ),
        ),
    ]
