# Generated by Django 5.2.13 on 2026-05-12 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_melario_numero_progressivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeteoGiornaliero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        help_text="Giorno solare in timezone locale dell'apiario"
                    ),
                ),
                ("temp_min", models.FloatField(blank=True, null=True)),
                ("temp_max", models.FloatField(blank=True, null=True)),
                ("temp_mean", models.FloatField(blank=True, null=True)),
                (
                    "precip_mm",
                    models.FloatField(
                        blank=True, help_text="Pioggia totale in mm", null=True
                    ),
                ),
                (
                    "precip_hours",
                    models.FloatField(
                        blank=True, help_text="Ore di precipitazione", null=True
                    ),
                ),
                (
                    "umidita_media",
                    models.FloatField(blank=True, help_text="% RH media", null=True),
                ),
                (
                    "vento_medio",
                    models.FloatField(
                        blank=True, help_text="km/h velocità media a 10m", null=True
                    ),
                ),
                (
                    "vento_raffica_max",
                    models.FloatField(
                        blank=True, help_text="km/h raffica massima", null=True
                    ),
                ),
                (
                    "pressione_media",
                    models.FloatField(
                        blank=True,
                        help_text="hPa pressione superficiale media",
                        null=True,
                    ),
                ),
                (
                    "ore_sole",
                    models.FloatField(
                        blank=True, help_text="Ore di sole effettive", null=True
                    ),
                ),
                (
                    "radiazione_mj",
                    models.FloatField(
                        blank=True,
                        help_text="MJ/m² radiazione solare globale giornaliera",
                        null=True,
                    ),
                ),
                (
                    "gdd_base10",
                    models.FloatField(
                        blank=True,
                        help_text="Growing Degree Days base 10°C: max(0, (tmin+tmax)/2 - 10)",
                        null=True,
                    ),
                ),
                (
                    "weather_code_dominante",
                    models.IntegerField(
                        blank=True, help_text="Codice WMO del giorno", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("archive", "Open-Meteo Archive (ERA5)"),
                            ("forecast", "Open-Meteo Forecast"),
                        ],
                        default="archive",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "apiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meteo_giornaliero",
                        to="core.apiario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meteo Giornaliero",
                "verbose_name_plural": "Meteo Giornalieri",
                "ordering": ["-data"],
                "indexes": [
                    models.Index(
                        fields=["apiario", "data"], name="idx_meteo_giorn_apiario_data"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("apiario", "data"),
                        name="uniq_meteo_giornaliero_apiario_data",
                    )
                ],
            },
        ),
    ]
