# Generated by Django 5.2.13 on 2026-05-25 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_ml_pesate_alimentazione_nomadismo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notifica",
            name="immagine_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notifica",
            name="link_param",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="notifica",
            name="link_route",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— Nessun link —"),
                    ("home", "Home / Dashboard"),
                    ("apiari", "Lista Apiari"),
                    ("arnie", "Lista Arnie"),
                    ("trattamenti", "Lista Trattamenti"),
                    ("melari", "Lista Melari"),
                    ("community", "Mappa Community"),
                    ("statistiche", "Statistiche"),
                    ("subscription", "Abbonamento"),
                    ("settings", "Impostazioni"),
                    ("whats_new", "Novità app"),
                    ("guida", "Guida"),
                    ("chat", "Chat AI"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="notifica",
            name="messaggio_html",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="notifica",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("invito_gruppo", "Invito Gruppo"),
                    ("membro_aggiunto", "Aggiunto al Gruppo"),
                    ("membro_rimosso", "Rimosso dal Gruppo"),
                    ("invito_accettato", "Invito Accettato"),
                    ("invito_rifiutato", "Invito Rifiutato"),
                    ("controllo_scaduto", "Controllo Scaduto"),
                    ("trattamento_scaduto", "Trattamento Scaduto"),
                    ("trattamento_promemoria", "Promemoria Trattamento"),
                    ("fioritura_vicina", "Fioritura Vicina"),
                    ("regina_assente", "Regina Assente"),
                    ("sistema", "Notifica di Sistema"),
                    ("broadcast", "Comunicazione Admin"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AdminBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titolo",
                    models.CharField(
                        help_text="Titolo breve mostrato anche nella push (max ~65 caratteri consigliati)",
                        max_length=200,
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        help_text="Corpo della notifica scritto con CKEditor (HTML)"
                    ),
                ),
                (
                    "immagine_url",
                    models.URLField(
                        blank=True,
                        help_text="URL di un'immagine banner opzionale (https://...)",
                        null=True,
                    ),
                ),
                (
                    "link_route",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "— Nessun link —"),
                            ("home", "Home / Dashboard"),
                            ("apiari", "Lista Apiari"),
                            ("arnie", "Lista Arnie"),
                            ("trattamenti", "Lista Trattamenti"),
                            ("melari", "Lista Melari"),
                            ("community", "Mappa Community"),
                            ("statistiche", "Statistiche"),
                            ("subscription", "Abbonamento"),
                            ("settings", "Impostazioni"),
                            ("whats_new", "Novità app"),
                            ("guida", "Guida"),
                            ("chat", "Chat AI"),
                        ],
                        default="",
                        help_text="Schermata dell'app aperta quando l'utente tocca la notifica",
                        max_length=30,
                    ),
                ),
                (
                    "link_param",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Parametro opzionale per il link (es. id arnia/apiario)",
                        max_length=100,
                    ),
                ),
                (
                    "priorita",
                    models.CharField(
                        choices=[
                            ("bassa", "Bassa"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                (
                    "pubblicata",
                    models.BooleanField(
                        default=False,
                        help_text="Quando spunti questa casella e salvi, la notifica viene inviata a tutti gli utenti",
                    ),
                ),
                ("data_pubblicazione", models.DateTimeField(blank=True, null=True)),
                ("destinatari_count", models.PositiveIntegerField(default=0)),
                (
                    "creata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcast_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicazione Broadcast",
                "verbose_name_plural": "Comunicazioni Broadcast",
                "ordering": ["-data_creazione"],
            },
        ),
        migrations.AddField(
            model_name="notifica",
            name="broadcast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifiche",
                to="core.adminbroadcast",
            ),
        ),
        migrations.AddIndex(
            model_name="notifica",
            index=models.Index(
                fields=["utente", "letta", "-data_creazione"],
                name="core_notifi_utente__8e4799_idx",
            ),
        ),
    ]
